# CameraMode Version 1.2.3
# Developed And Maintained By xYourFreindx
# http://dev.bukkit.org/bukkit-plugins/cameramode/pages/config-yml-explained/
CameraMode:
    Enabled: true
    Updates:
        AutoUpdate: false
        NotifyOps: true
    PvpTimer: 8
    PlayersInCM:
        AreInvincible: true
        AreVanished: false
        CanChangeWorlds: true
        CanUseCommands: false
        AllowedCommands:
        - camera
        - cameramode
        - cm
    CameraTimeLimit: 35
    CameraCoolDown: 15