#CameraMode Version 1.1.2 Beta
#Developed And Maintained By xYourFreindx
CameraMode:
    Enabled: true
    PlayersInCM:
        AreInvincible: true
        AreVanished: false
        CanChangeWorlds: true
        CanUseCommands: true
        #Only Necessary if "CanUseCommands" is set to false.
        AllowedCommands:
        - camera
        - cameramode
        - reload
        - save-all
        
        
        
