name: CameraMode
main: com.gmail.justisroot.cameramode.CameraMode
version: 1.2.3

commands:
    cameramode:
        usage: /cameramode
        description: Puts player in cameramode
        aliases: [cm,cmode, cammode]
    camera reload:
        usage: /cameramode reload
        description: Reloads config
        aliases: [camera save]
    camera:
        usage: /camera
        description: opens the help page
        aliases: [cam]
permissions:
    cameramode.*:
        description: Give access to all CameraMode permissions
        children:
            cameramode.fly: true
            cameramode.camera: true
            cameramode.reload: true
            cameramode.cm: true
            cameramode.other: true
            cameramode.config: true
            cameramode.update: true
        default: op
    cameramode.cm:
        description: Gives access to cameramode
        default: true
    cameramode.fly:
        description: Allows players to survival fly even when not in camera mode. (only necessary if they have safefly.fly)
        default: op
    cameramode.reload:
        description: Allows access to /camera reload
        default: op
    cameramode.camera:
        description: shows available commands
        default: true
    cameramode.other:
        description: Give and take CameraMode to/from other players
        default: op
    cameramode.config:
        description: Allow for configuration of the config file.
        default: op
    cameramode.update:
        description: Grants notification to updates.
        default: op