name: CameraMode
main: com.gmail.justisroot.cameramode.CameraMode
version: 1.0.3 

commands:
    cameramode:
        usage: /cameramode
        description: Puts player in cameramode
        aliases: [cm]
    camera reload:
        usage: /cameramode reload
        description: Reloads config
        aliases: [camera save]
    camera:
        usage: /camera
        description: opens the help page
permissions:
    cameramode.*:
        description: Give access to all CameraMode permissions
        children:
            cameramode.fly: true
            cameramode.camera: true
            cameramode.reload: true
            cameramode.cm: true
        default: op
    cameramode.cm:
        description: Gives access to cameramode
        default: false
    cameramode.fly:
        description: Allows players to survival fly even when not in camera mode. (only necessary if they have safefly.fly)
        default: op
    cameramode.reload:
        description: Allows access to /camera reload
        default: op
    cameramode.camera:
        description: shows available commands
        default: true